### PR TITLE
Rename "username" parameter to "user" at `OdbcDriver` in order to be consistent with other "doctrine/dbal" drivers

### PR DESCRIPTION
**Pull request by phansys**
See [Configuration > Configuration details](https://github.com/doctrine/dbal/blob/3.6.x/docs/en/reference/configuration.rst#connection-details).

### CODE REVIEW

**Comment by NattyNarwhal** [comment]
Does this cause any BC break, or is this just internal to Doctrine drivers?

**Comment by NattyNarwhal** [comment]
It might be worth checking both then; I'm uncertain about use in the wild.

**Comment by phansys** [comment]
>It might be worth checking both then; I'm uncertain about use in the wild.

I've added a new commit with the proposed deprecation. Please, let me know if you think we must keep this deprecation path or just make this change without notice.

**Comment by NattyNarwhal** [comment]
I think this should be good.

**Pull request merged**
